### ISSUE TITLE
Add DataConverter to ActivityOptions

### ISSUE THREAD

**Issue by mfateev** [uber/cadence-java-client#266]
Currently there is no way to override a DataConverter for individual activity stub. The solution is to add DeataConverter to ActivityOptions.

**Comment by meiliang86** [comment]
DataConverter cannot be serialized. So I don't think this can be reliably stored and used during replay.
What is the requirement here? Is it to have a data converter for activities v.s. workflows, or to have a data converter override for a single activity?
Currently we have data converter in worker options. We can have a separate account data converter in worker options, but it does not seem to make sense to have them in workflow options/ activity options.
