### ISSUE TITLE
Unclear description about versioning in README.md

### ISSUE THREAD

**Issue by jontro** [uber/cadence-java-client#271]
Currently the readme states 

> Don't change workflow code when there are open workflows. The ability to do updates through versioning is TBD."

However [Workflow::getVersion](https://github.com/uber/cadence-java-client/blob/cc7182902778eba4c7c1356ffd4d2a11ded83cc5/src/main/java/com/uber/cadence/workflow/Workflow.java#L938) states how it should be done.

I had to do a little digging to find this and maybe a note pointing to the javadoc would be helpful for newcomers

**Comment by mfateev** [comment]
Thanks for reporting. We are going to update the documentation.

**Comment by mfateev** [comment]
https://github.com/uber/cadence-java-client/pull/288

**Comment by dmetzgar** [comment]
Incorporated changes from #288 into #279. This issue can be closed.
