### ISSUE TITLE
[Question] How do I reassign activities to a new host that is added to an auto scaling group.

### ISSUE THREAD

**Issue by jbotaldrich** [uber/cadence-java-client#301]
This is a general question.  I have my workers running in an autoscaling group.  It scales up and down based on cpu utilization.  I find if a workflow has many parallel jobs running they are all assigned to the hosts that are currently available and never get reassigned to the new host.  

Is there a convention to this?  I read somewhere to use a "scheduled to start" timeout that is relatively small and use retries which have a long expiration. Will this cause it to reschedule with a new host or will it continue to retry on the previously selected host?  Thanks!

**Comment by jbotaldrich** [comment]
Another question.  Is there any way to heartbeat in a separate thread.  The documentation just shows a for loop being updated with Activity.heartbeat(details).  I have long-running analysis processes running in Docker containers managed by the activities.  I would like to heartbeat in case something happens with the host so it can be retried elsewhere.  I tried starting a "heartbeat thread" which has a scheduled heartbeat interval but the Activity definitely didn't like that.  Any suggestions?

**Comment by mfateev** [comment]
Sorry, missed the question among other issues. To get faster reply better submit the question on [stackoverflow](https://stackoverflow.com/questions/tagged/cadence-workflow) under cadence-workflow tag or reach us through [slack](https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTQyYjcxZDM2YTIxMTZkMzQ0NjgxYmI3OWY5ODhiOTliM2I5MzA4NTM4MjU4YzgzZDkwNGEzOTUzNTBlNDk3Yjc).

**Comment by mfateev** [comment]
Activities are not assigned to any host until started. So for short lived activities adding new host automatically distributes load to it. 

For long lived ones it is more complicated as it would require preemption. It can be done by cancelling activities and rescheduling them to another hosts. But in this case the workflow must know about the load distribution. Let us know if you are trying to solve the preemption and we can work on the design.

**Comment by mfateev** [comment]
Second question. You have two options:

- Heartbeat from the main thread and run analysis process in its own thread.

- Heartbeat from any thread using ActivityCompletionClient. See [this sample for ](https://github.com/uber/cadence-java-samples/blob/master/src/main/java/com/uber/cadence/samples/hello/HelloAsyncActivityCompletion.java) details.

**Comment by jbotaldrich** [comment]
Thank you so much!  The first option is pretty obvious now that you mention it but it seems weird to have the purpose of the activity in a separate thread.  I think I like the second option.  Thanks for your help.  I think with the heartbeat thread I should be able to reschedule at least the failed jobs in a more timely manner.  The preemption problem is something I'm interested in but may have to circle back in a few weeks as time permits.

Also, I'll use the options you mentioned next time for questions and I appreciate the response.
