### ISSUE TITLE
Add missing fields to ContinueAsNewOptions

### ISSUE THREAD

**Issue by mfateev** [uber/cadence-java-client#304]
ContinueAsNewWorkflowExecutionDecisionAttributes
  public WorkflowType workflowType; // optional
  public TaskList taskList; // optional
  public ByteBuffer input; // optional
  public int executionStartToCloseTimeoutSeconds; // optional
  public int taskStartToCloseTimeoutSeconds; // optional
  public int backoffStartIntervalInSeconds; // optional
  public RetryPolicy retryPolicy; // optional
  public ContinueAsNewInitiator initiator; // optional
  public String failureReason; // optional
  public ByteBuffer failureDetails; // optional
  public ByteBuffer lastCompletionResult; // optional
  public String cronSchedule; // optional

public final class ContinueAsNewOptions {
    private Duration executionStartToCloseTimeout;
    private String taskList;
    private Duration taskStartToCloseTimeout;

**Comment by meiliang86** [comment]
@mfateev Glancing at this list, it seems that the only thing that makes sense to add but is currently missing is retryPolicy?
