### ISSUE TITLE
Add WorkflowClient.shutdown

### ISSUE THREAD

**Issue by mfateev** [uber/cadence-java-client#344]
Currently there is no way to shutdown IWorkflowService from WorkflowClient.

**Comment by 14417335** [comment]
Thanks to @mfateev 's recommendation, other than the System.Exit() approach which could be too destructive in many occasions, there's another work-around to cleanly close up:
`    WorkflowServiceTChannel chan = new WorkflowServiceTChannel(CADENCE_HOST, CADENCE_PORT);
    WorkflowClient workflowClient = WorkflowClient.newInstance(chan, DOMAIN);

    // wrap the following in finally to guarantee execution
    chan.close();
`
