### ISSUE TITLE
Add before/after methods to workflow interceptor.

### ISSUE THREAD

**Issue by mfateev** [uber/cadence-java-client#350]
[WorkflowInterceptor](https://github.com/uber/cadence-java-client/blob/7912a840aefdd3f1ebdb96f94d709f874b95bc44/src/main/java/com/uber/cadence/workflow/WorkflowInterceptor.java#L32:18) lacks methods that are invoked before the workflow is started and after it completes.

They might be necessary to inject appropriate thread local variables.

**Comment by JuanPalacios** [comment]
Hello Maxim,
Is there any posibility to create the start and after interceptor in the current version?
We want to add our status custom logic in these point.

Thanks

**Comment by mfateev** [comment]
The current interceptor is far from ideal, but should be Ok for your use case:
https://github.com/uber/cadence-java-client/blob/d56612f05108efd4696310935d99def3a794f915/src/main/java/com/uber/cadence/worker/WorkerOptions.java#L174
