### ISSUE TITLE
Add missing metrics from go client

### ISSUE THREAD

**Issue by vancexu** [uber/cadence-java-client#379]
Need to find all missing metrics from go client and add them, such as `activity-scheduled-to-start-latency`

**Comment by aai95** [comment]
Hello @vancexu
I have signed Uber CLA.
Could you please assign this issue to me?
Also, the target branch for my PR is master, right?

**Comment by aai95** [comment]
@vancexu
As I understand, the following Go metrics have their semantic copy in Java:
Go `decision-task-panic` has name in Java `decision-task-error`
Go `decision-task-force-completed` **should be added**
Go `activity-task-panic` has name in Java `activity-task-error`
Go `sticky-cache-evict` has names in Java `sticky-cache-total-forced-eviction` and `sticky-cache-thread-forced-eviction`
Go `non-deterministic-error` **should be added**

I can't find proper place in Java client for adding of this two metrics.
Do we already have required functionality implementation for injection of this two metrics?

Thank you in advance for your assistance!

**Comment by vancexu** [comment]
> Hello @vancexu
> I have signed Uber CLA.
> Could you please assign this issue to me?
> Also, the target branch for my PR is master, right?

Thank you for the contribution! 
Yes, target branch is master
