### ISSUE TITLE
Add support for ParentClosePolicy option

### ISSUE THREAD

**Issue by mfateev** [uber/cadence-java-client#433]
It looks like Java client still doesn't support [ParentClosePolicy](https://github.com/uber/cadence-idl/blob/a62e74b9e0d5b02fccdf046208c0ce57e54d4591/thrift/shared.thrift#L137). 

Also remove [all references](https://github.com/uber/cadence-java-client/blob/master/src/main/java/com/uber/cadence/internal/external/GenericWorkflowClientExternalImpl.java#L126) to childPolicy.

**Comment by RemcoBuddelmeijer** [comment]
@mfateev I can pick this up today

**Comment by RemcoBuddelmeijer** [comment]
I have removed all references to ChildPolicy from the Java Client, this includes the code, thrift shared objects and the test input files.

**Comment by RemcoBuddelmeijer** [comment]
Issue can be closed as the PR has been merged.
