### ISSUE TITLE
Noisy error log when poller returns with no task

### ISSUE THREAD

**Issue by venkat1109** [uber/cadence-java-client#464]
One of our customers reported this error. Didn't dig deeper, it looks like poller logs this error when there is no task from the server.  

com.uber.cadence.internal.worker.Poller: Failure in thread Workflow Poller taskList="xxxTaskList", domain="xxx": 1 org.apache.thrift.TException: Rpc error:<ErrorResponse id=229 errorType=Timeout message=Request timeout after 121006ms>

**Comment by meiliang86** [comment]
https://github.com/uber/cadence-java-client/commit/83973b32b420ae3d8037b88b103d9de06bc140f6
