### ISSUE TITLE
Consider supporting fully async workflow implementation

### ISSUE THREAD

**Issue by mfateev** [uber/cadence-java-client#47]
For high rate workflows using blocking model with a thread pool might be prohibitive
Anther option is to use Kotlin coroutines for such use cases.

**Comment by jontro** [comment]
One question related to this, if we're creating a bunch of long running workflows (let's say 10k a day) which last for a month, will this consume 300k sleeping threads in the end?

**Comment by mfateev** [comment]
No, as workflows are pushed out of the cache the threads are released. 

The reason for this issue is that synchronous workflows can be cached up to number of available threads. Loading a workflow to cache consumes resources. So for high throughput scenarios (1k + workflows per second) having  large caches is important.

**Comment by ibarrajo** [comment]
We have a few async java examples:
https://github.com/uber/cadence-java-samples/blob/1fa035a81d628919ae05dbb60e8d40ec6adacdd8/README.md
