### ISSUE TITLE
cadenceworkflow.io javaclient link is not working in README.md

### ISSUE THREAD

**Issue by DhiralKaniya** [uber/cadence-java-client#516]
README.md link :- https://github.com/uber/cadence-java-client

Text for link :- The documentation on how to use the Cadence Java client is here.
Link which is not working :- https://cadenceworkflow.io/docs/06_javaclient/

**Comment by just-at-uber** [comment]
This should be pretty easy to fix. Will fix when I have some free downtime.

**Comment by just-at-uber** [comment]
Following up on this task:

https://cadenceworkflow.io/docs/java-client/ 

is the correct link to use here.
