### ISSUE TITLE
Confusing naming convention of MethodRetry annotation doNotRetry parameter

### ISSUE THREAD

**Issue by mwoss** [uber/cadence-java-client#579]
Hi all :DD!
I have a question regarding the `doNotRetry` parameter of MethodRetry annotation. As the name suggests, I would expect this parameter accepts an exception or a list of exceptions that will be used as information for Cadence workers or server to know when  **do not retry** activity exception is thrown. 
However, according to the documentation, this annotation parameter is used to tell workers/server on which exception the activity **must be retried**. This is a contradiction in my opinion. 

~~Looking at [clinet code](https://github.com/uber/cadence-java-client/blob/master/src/main/java/com/uber/cadence/common/RetryOptions.java#L407-L424) I will assume that the second option is correct. In that case, should `doNotRetry` parameter be renamed to `doRetry` or something similar?~~

Edit: Apologies, I think I was wrong. The parameter does exactly what it should do, but still, documentation is a bit misleading and in my opinion, should be corrected. 

Documentation: [Java doc - MathodRetry, doNotRetry paramater](https://www.javadoc.io/doc/com.uber.cadence/cadence-client/2.4.1/com/uber/cadence/common/MethodRetry.html#doNotRetry--)

**Comment by demirkayaender** [comment]
Closing old issues. Please reopen if you still need help
