### ISSUE TITLE
getScheduledTimestamp returns micro seconds not milliseconds 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence-java-client#583]
https://github.com/uber/cadence-java-client/blob/14e523a7a0eae4b8ce671c07284da1c66261287c/src/main/java/com/uber/cadence/internal/sync/ActivityTaskImpl.java#L57

In Cadence server, timestamp is based on nanoSecond, not microSecond.

**Comment by Hart87** [comment]
I'm looking at this bug but my entire screen is lit up with "cannot resolve symbol" errors. Do you have the same issue? It's for the methods pertaining to these imports 
import com.uber.cadence.PollForActivityTaskResponse;
import com.uber.cadence.WorkflowExecution;
import com.uber.cadence.WorkflowType;

**Comment by jsferner** [comment]
No I never had any issues like that
