### ISSUE TITLE
Implement Memo/SearchAttributes for ChildWorkflow

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence-java-client#615]
It's in ChildWorkflowOptions but never being applied into the StartChildWorkflow code path. 

It should be pretty straightforward following other entities, especially searchAttributes

**Comment by avitkovskaya-syberry** [comment]
@longquanzheng Hi, is there and updates about this issue? Tried to implement searchAttributes  for childWorkflow, but it didn't worked

**Comment by longquanzheng** [comment]
Hi @avitkovskaya-syberry search attributes are already implemented, see https://www.javadoc.io/doc/com.uber.cadence/cadence-client/latest/com/uber/cadence/workflow/ChildWorkflowOptions.Builder.html

**Comment by avitkovskaya-syberry** [comment]
@longquanzheng I check it. I run childworkflows with search attributes and they are not indexed in ES. 
If to follow java client code seems they are ignored and not mapped in StartChildWorkflowExecutionParameters
https://github.com/uber/cadence-java-client/blob/d8b08b0b5f4e491abfee64eb5c32cc1b03fccbd0/src/main/java/com/uber/cadence/internal/sync/SyncDecisionContext.java#L403

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence-java-client/pull/641

**Comment by longquanzheng** [comment]
Implemented in the above  pr
