### ISSUE TITLE
Add a new tag to differentiate long-poll and non-long-poll requests for GetWorkflowExecutionHistory API

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence-java-client#649]
https://github.com/uber/cadence-java-client/blob/dca853aaa047071caab8b16a345474aa3708d162/src/main/java/com/uber/cadence/serviceclient/WorkflowServiceTChannel.java#L668

This will be important for make sure non-long poll is not running into high latency issue.

**Comment by jakobht** [comment]
This is already done, see:

https://github.com/uber/cadence-java-client/blob/8fddf993eb199b776c45e9187ace3437f297c907/src/main/java/com/uber/cadence/serviceclient/WorkflowServiceTChannel.java#L625
