### ISSUE TITLE
cron-utils critical vulnerability

### ISSUE THREAD

**Issue by bw-abrowne** [uber/cadence-java-client#742]
cron-utils v 9.0.0 has a critical vulnerability via arbitrary Java EL expressions. This dependency should be updated, if possible, to 9.2.0. For more information, see the snyk description [here](https://security.snyk.io/vuln/SNYK-JAVA-COMCRONUTILS-1921097).

**Comment by mindaugasbarcauskas** [comment]
Updated in https://github.com/uber/cadence-java-client/pull/766
