### ISSUE TITLE
Missing release 3.7.3 artifacts in Maven Repository.

### ISSUE THREAD

**Issue by matteeos** [uber/cadence-java-client#747]
Missing latest release 3.7.3 artifacts in Maven Repository.
https://mvnrepository.com/artifact/com.uber.cadence/cadence-client

**Comment by matteeos** [comment]
Any update on that as version 3.8.0 was released?

**Comment by mindaugasbarcauskas** [comment]
@matteeos Working on adding 3.7.3 to public maven repository.

**Comment by mindaugasbarcauskas** [comment]
@matteeos 3.7.3 cadence-client should be available in central repository in an hour, will publish 3.8.0 to central repository next week.
