### ISSUE TITLE
Dependency issuew with new 3.9.0 version #765

### ISSUE THREAD

**Issue by radekoziol** [uber/cadence-java-client#830]
Hi guys,

In the new release `io.grpc:grpc-testing` dependecy was [updated](https://github.com/uber/cadence-java-client/compare/v3.8.1...v3.9.0#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R72) to `1.51.0` however others like `io.grpc:grpc-netty-shaded: 1.28.0` were not updated. Those two versions are not compatible so now our app to fails to initialize:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void io.grpc.internal.AbstractManagedChannelImplBuilder.<init>(java.lang.String)'
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:136)
         ...
```

We will naturally exclude `io.grpc:grpc-testing` however can you move `grpc-testing` to test dependencies or update others so it's consistent?

**Comment by natemort** [comment]
Fixed in https://github.com/uber/cadence-java-client/pull/858
